# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and test
        run: chmod u+rx millw && ./millw -i main.testAll

  cli-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build CLI
        run: chmod u+rx millw && ./millw -i cli.nativeLink && ./millw -i cli.assembly
      - name: Upload native artifact
        uses: actions/upload-artifact@v3
        with:
          name: cylang-ubuntu
          path: out/cli/nativeLink.dest/out
      - name: Upload JVM artifact
        uses: actions/upload-artifact@v3
        with:
          name: cylang-jvm
          path: out/cli/assembly.dest/out.jar

  cli-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build CLI
        run: chmod u+rx millw && ./millw -i cli.nativeLink
      - name: Upload native artifact
        uses: actions/upload-artifact@v3
        with:
          name: cylang-windows
          path: out/cli/nativeLink.dest/out