# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  pages: write
  id-token: write

# Controls when the action will run.
on:
  push:
    branches: [main] # Must be changed to `main` once released

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish-website"
  publish-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build editor
        run: chmod u+rx millw && ./millw webeditor.buildSite

      - name: Build site
        run: cd webeditor && npm install && npm run gh-build

      - uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: webeditor/dist

      - uses: actions/deploy-pages@v1.0.10